# Generated by Django 5.1.4 on 2025-01-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='biography',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='your_email',
        ),
    ]
