# Generated by Django 5.1.4 on 2025-01-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_biography_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='your_email',
            field=models.EmailField(max_length=254),
        ),
    ]
